name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Aqui criamos o arquivo config.json usando os segredos
    - name: Create config.json
      run: |
        echo '{
          "share_point": {
            "user": "'${{ secrets.SHAREPOINT_USER }}'",
            "password": "'${{ secrets.SHAREPOINT_PASSWORD }}'",
            "url": "'${{ secrets.SHAREPOINT_URL }}'",
            "doc_library": "'${{ secrets.SHAREPOINT_DOC_LIBRARY }}'"
          }
        }' > config.json

    - name: Run Python script
      run: python project.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Auto update HTML"
        git push
